dataset:
  repo_id: repo_smolvla
  root: Datasets/four_types_merged_combined
  video_backend: pyav
policy:
  type: smolvla
  device: cuda
  push_to_hub: false
  
  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.top_depth:
      type: STATE
      shape: [1, 480, 640]
  
  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/four_types_merged_combined_smolvla
batch_size: 32
steps: 60000
save_freq: 1000
log_freq: 500

wandb:
  enable: false